name: admin
description: Mobile Admin Panel.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  data_table_2: ^2.2.0
  package_info_plus: ^3.0.2
  flutter_form_builder: ^7.0.0
  flutter_svg: ^0.23.0+1
  fl_chart: ^0.40.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^4.0.4
  provider: ^6.0.1
  firebase_core: ^2.16.0
  firebase_core_web: ^2.8.0
  firebase_database: ^10.2.6
  firebase_core_platform_interface: ^4.8.0
  firebase_storage: ^11.2.7
  mocktail: ^0.3.0
  firebase_database_mocks: ^0.6.0
  image_picker: ^0.8.7+1

  app_version_update:
    git:
      url: https://github.com/Etiya/admin_panel_packages
      path: packages/app_version_update

  maintenance_mode:
    git:
      url: https://github.com/Etiya/admin_panel_packages
      path: packages/maintenance_mode
  firebase_auth: ^4.10.0
  flutter_screenutil: ^5.9.0
  mockito: ^5.3.2
  firebase_auth_mocks: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   package_info_plus: ^4.0.1
#   wakelock_windows: any
#   win32: any

  flutter_lints: ^1.0.4

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
