// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhdvuq2QGMfCXvOfP_RXa0FRG9Zkkob0Q',
    appId: '1:891043151640:web:736fd6b1d4f5bed38e686d',
    messagingSenderId: '891043151640',
    projectId: 'mobileadminpanel',
    authDomain: 'mobileadminpanel.firebaseapp.com',
    databaseURL: 'https://mobileadminpanel-default-rtdb.firebaseio.com',
    storageBucket: 'mobileadminpanel.appspot.com',
    measurementId: 'G-S9MRF7YZ3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzWKofyjeotVGabo8PdVfV_ZwzOspX3I',
    appId: '1:891043151640:android:71de5164591a5f128e686d',
    messagingSenderId: '891043151640',
    projectId: 'mobileadminpanel',
    databaseURL: 'https://mobileadminpanel-default-rtdb.firebaseio.com',
    storageBucket: 'mobileadminpanel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsKLPqY-nSTvalZHhIYyZmvRqZMEMdrY',
    appId: '1:891043151640:ios:6bfcd3bc053c14ae8e686d',
    messagingSenderId: '891043151640',
    projectId: 'mobileadminpanel',
    databaseURL: 'https://mobileadminpanel-default-rtdb.firebaseio.com',
    storageBucket: 'mobileadminpanel.appspot.com',
    iosClientId: '891043151640-cit846hto04035d4tbt1865ms56d3ig9.apps.googleusercontent.com',
    iosBundleId: 'com.etiya.mobileadminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsKLPqY-nSTvalZHhIYyZmvRqZMEMdrY',
    appId: '1:891043151640:ios:6bfcd3bc053c14ae8e686d',
    messagingSenderId: '891043151640',
    projectId: 'mobileadminpanel',
    databaseURL: 'https://mobileadminpanel-default-rtdb.firebaseio.com',
    storageBucket: 'mobileadminpanel.appspot.com',
    iosClientId: '891043151640-cit846hto04035d4tbt1865ms56d3ig9.apps.googleusercontent.com',
    iosBundleId: 'com.etiya.mobileadminpanel',
  );
}
